#define HAVE_LOCALE_H 1
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_FCNTL_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_GRP_H 1
#define HAVE_PWD_H 1
#define X_HAVE_UTF8_STRING 1
#define PACKAGE_NAME "openbox"
#define PACKAGE_VERSION "3.5.0-duzy"
#define PACKAGE_BUGREPORT "code@duzy.info"
#define DATADIR ""
#define LOCALEDIR DATADIR"/locale"
#define CONFIGDIR ""
#define DEFAULT_THEME "Clearlooks"
